name: Linter

on: [push, pull_request]

jobs:
  format-and-lint:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Run the linter
        run: |
          yarn install
          yarn run linter
